for bnr_set in DEPOT_PUBLIC    RBX_AMR_2F1	RBX_AMR_AFF	RBX_AMR_AMD	RBX_AMR_AME	RBX_AMR_AMF	RBX_AMR_AMK	RBX_AMR_AMR	RBX_AMR_CAD	RBX_AMR_DEL	RBX_AMR_FOR	RBX_AMR_GUE	RBX_AMR_LEB	RBX_AMR_OBJ	RBX_AMR_PHO	RBX_AMR_PLA	RBX_AMR_PR	RBX_AMR_PUV	RBX_AMR_RAM	RBX_AMR_VIC	RBX_ARA_CPS	RBX_CHR_PHO	RBX_CSV_PAL	RBX_LAI	RBX_LAR_PUB	RBX_MDF_MTX	RBX_MED_AFF	RBX_MED_CAT	RBX_MED_CHA	RBX_MED_COM	RBX_MED_CP	RBX_MED_DIL	RBX_MED_EPH	RBX_MED_FLR	RBX_MED_FOO	RBX_MED_IMA	RBX_MED_LET	RBX_MED_MAR	RBX_MED_MEU	RBX_MED_MON	RBX_MED_MS	RBX_MED_PAR	RBX_MED_PHO	RBX_MED_PIA	RBX_MED_PLA	RBX_MED_PRO	RBX_MED_PUB	RBX_MED_RAD	RBX_MED_VDM	RBX_MUS_ARC	RBX_MUS_VAI	RBX_OBS_JOU	RBX_PRA_AVE	RBX_PRA_CRT	RBX_PRA_CTG	RBX_PRA_ERT	RBX_PRA_IND	RBX_PRA_JRX	RBX_PRA_RTG	RBX_VAH_PUB	RES_WEB
do
    echo $bnr_set
    catmandu convert OAI --url http://oai.bn-r.fr/oai.php --metadataPrefix oai_dc --set $bnr_set --fix "add_field(bnr_set, $bnr_set)" to JSON > results/bnr_set_$bnr_set.json
done

#catmandu convert OAI --url http://oai.bn-r.fr/oai.php --metadataPrefix oai_dc --set RBX_MED_AFF to JSON
